# Generated by Django 4.0.4 on 2022-04-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_diak_pontszam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diak',
            old_name='Atagozat',
            new_name='angol',
        ),
        migrations.RenameField(
            model_name='diak',
            old_name='Btagozat',
            new_name='matek',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Ctagozat',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Dtagozat',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Etagozat',
        ),
        migrations.RemoveField(
            model_name='diak',
            name='Ftagozat',
        ),
    ]
